### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

############ Medications ############
### Medication Index
GET http://localhost:3000/medications.json

### Medication Show
GET http://localhost:3000/medications/1.json

### Medication Create
POST http://localhost:3000/medications.json
Content-Type: application/json

{
  "name": "metformin",
  "amount": 1,
  "measurement": "tablet",
  "frequency": 3
}

### Medication Update
PATCH http://localhost:3000/medications/2.json
Content-Type: application/json

{
  "name": "Prinvil",
  "directions": "Take 1 tablet (10mg) by mouth daily."
}

### Medication Destroy
DELETE http://localhost:3000/medications/4.json
